package com.deongao.examquestionrepo.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.deongao.examquestionrepo.model.ExamQuestion;

import com.deongao.examquestionrepo.greendao.ExamQuestionDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig examQuestionDaoConfig;

    private final ExamQuestionDao examQuestionDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        examQuestionDaoConfig = daoConfigMap.get(ExamQuestionDao.class).clone();
        examQuestionDaoConfig.initIdentityScope(type);

        examQuestionDao = new ExamQuestionDao(examQuestionDaoConfig, this);

        registerDao(ExamQuestion.class, examQuestionDao);
    }
    
    public void clear() {
        examQuestionDaoConfig.getIdentityScope().clear();
    }

    public ExamQuestionDao getExamQuestionDao() {
        return examQuestionDao;
    }

}
